package org.seda.payer.manager.util;

import java.text.MessageFormat;
import java.util.ResourceBundle;
/**
 * 
 * @author mmontisano
 *
 */
public enum Field {
	TX_MOSTRA, 
	TX_INDIRIZZO_IP, 
	TX_USER_EMAIL, 
	TX_NEW_USER_EMAIL, 
	TX_USER_SMS,
	TX_NEW_USER_SMS,
	TX_CODICE_TRANSAZIONE,
	TX_CODICE_TRANSAZIONE_HIDDEN, 
	TX_TIPO_CARTA, 
	TX_TIPO_CARTA_WRSXML, 
	TX_TIPOLOGIA_SERVIZIO,
	TX_TIPOLOGIA_SERVIZIO_SEL,
	TX_TIPOLOGIA__WRSXML, 
	TX_CANALE_PAGAMENTO, 
	TX_CANALE_PAGAMENTO_WRSXML, 
	TX_SOCIETA, 
	TX_SOCIETA_WRSXML, 
	TX_DATA_A, 
	TX_DATA_DA, 
	TX_ENTE,
	TX_UTENTE,
	TX_UTENTE_ENTE,
	TX_ID_BOLLETTINO,
	TX_PROVINCIA,
	TX_STATO_RENDICONTAZIONE,
	TX_STATO_RICONCILIAZIONE,
	TX_STRUMENTO,
	TX_BUTTON_CERCA, 
	TX_BUTTON_RESET, 
	TX_BUTTON_COMUNE_CHANGED,
	TX_BUTTON_EDIT,
	TX_BUTTON_STAMPA,
	TX_BUTTON_DOWNLOAD,
	TX_BUTTON_SOCIETA_CHANGED,
	TX_BUTTON_PROVINCIA_CHANGED,
	TX_BUTTON_UTENTE_CHANGED,
	//riversamento beneficiario
	TX_BUTTON_SOCIETA_BEN_CHANGED,
	TX_BUTTON_PROVINCIA_BEN_CHANGED,
	TX_BUTTON_UTENTE_BEN_CHANGED,

	TX_BUTTON_ENTE_CHANGED,
	TX_BUTTON_IMPOSITORE_CHANGED,
	TX_BUTTON_AGGIUNGI,
	TX_BUTTON_DELETE,
	TX_BUTTON_EDIT_END,
	TX_BUTTON_AGGIUNGI_END,
	TX_BUTTON_CANCEL,
	TX_BUTTON_MOVIMENTO_CHANGED,
	FIRED_BUTTON_HIDDEN,
	TX_MESSAGE,
	TX_ERROR_MESSAGE,
	TX_DATA_A_DAY,
	TX_DATA_A_MONTH,
	TX_DATA_A_YEAR,
	TX_DATA_DA_DAY,
	TX_DATA_DA_MONTH,
	TX_DATA_DA_YEAR,
	TX_IMPORTO_DA,
	TX_IMPORTO_A,
	TX_CHIAVE_QUADRATURA,
	USER_LEVEL, 
	ORDER_BY, 
	PAGE_NUMBER, 
	PAGE_NUMBER_HIDDEN,
	ROWS_PER_PAGE,
	TX_LISTA,
	TX_LISTA_PAGEINFO,
	TX_LISTA_GROUPED,
	TX_LISTA_ONERI_GROUPED,
	TX_LISTA_GROUPED_SUCCESS,
	GROUPED_TOTAL,
	GROUPED_SUCCESS_TOTAL,
	TX_TRANSAZIONE,
	TX_LISTA_ICI,
	TX_LISTA_FRECCIA,
	TX_LISTA_DETTAGLIO,
	TX_LISTA_ONERI,
	TX_CODICE_IDENTIFICATIVO_BANCA,
	TX_CODICE_AUTORIZZAZIONE_BANCA,
	TX_DATA_PAGAMENTO,
	TX_DATA_PAGAMENTO_DAY,
	TX_DATA_PAGAMENTO_MONTH,
	TX_DATA_PAGAMENTO_YEAR,
	TX_ORA_PAGAMENTO,
	TX_MINUTI_PAGAMENTO,
	TX_NOTE,
	TX_CHIAVE_GATEWAY,
	TX_CODICE_GATEWAY,
	TX_TIPO_FLUSSO,
	LISTA_FLUSSI,
	LISTA_FLUSSI_PAGEINFO,
	LISTA_FLUSSI_RIEPILOGO,
	TX_CHIAVE_RENDICONTAZIONE,
	TX_NOME_FLUSSO,
	TX_DATA_PAGAMENTO_DA,
	TX_DATA_PAGAMENTO_A,
	TX_DATA_CREAZIONE_DA,
	TX_DATA_CREAZIONE_A,
	TX_ID_TRANSAZ_ATM,
	TX_ID_TERMINALE_POS_FISICO,
	TX_CODICE_IUV,	//PG150180_001 GG
	TX_CODICE_IUR,	//PG160230_001 GG
	TX_ID_LOGREQUEST,
	// campi del form di riconciliazione
	CHIAVE_MOVIMENTO,
	MOSTRA_MOVIMENTI,
	CODICE_ABI,
	CODICE_CAB,
	CODICE_SIA,
	CRO,
	CCB,
	NOME_SUPPORTO,
	IMPORTO_MOVIMENTO_A,
	IMPORTO_MOVIMENTO_DA,
	DATA_CREAZIONE_A,
	DATA_CREAZIONE_A_DAY,
	DATA_CREAZIONE_A_MONTH,
	DATA_CREAZIONE_A_YEAR,
	DATA_CREAZIONE_DA,
	DATA_CREAZIONE_DA_DAY,
	DATA_CREAZIONE_DA_MONTH,
	DATA_CREAZIONE_DA_YEAR,
	DATA_VALUTA_A,
	DATA_VALUTA_A_DAY,
	DATA_VALUTA_A_MONTH,
	DATA_VALUTA_A_YEAR,
	DATA_VALUTA_DA,
	DATA_VALUTA_DA_DAY,
	DATA_VALUTA_DA_MONTH,
	DATA_VALUTA_DA_YEAR,
	DATA_CONTABILE_A,
	DATA_CONTABILE_A_DAY,
	DATA_CONTABILE_A_MONTH,
	DATA_CONTABILE_A_YEAR,
	DATA_CONTABILE_DA,
	DATA_CONTABILE_DA_DAY,
	DATA_CONTABILE_DA_MONTH,
	DATA_CONTABILE_DA_YEAR,
	LISTA_MOVIMENTI,
	LISTA_MOVIMENTI_PAGEINFO,
	LISTA_MOVIMENTI_GROUPED,
	// campi del form di riconciliazione manuale
	CHIAVE_TRANSAZIONE,
	RIFERIMENTO_MOVIMENTO,
	DATA_PAGAMENTO_A,
	DATA_PAGAMENTO_A_DAY,
	DATA_PAGAMENTO_A_MONTH,
	DATA_PAGAMENTO_A_YEAR,
	DATA_PAGAMENTO_DA,
	DATA_PAGAMENTO_DA_DAY,
	DATA_PAGAMENTO_DA_MONTH,
	DATA_PAGAMENTO_DA_YEAR,
	LISTA_MOVIMENTI_APERTI,
	LISTA_TRANSAZIONI_NQ,
	LISTA_TRANSAZIONI_NQ_PAGEINFO,
	RIEPILOGO_TRANSAZIONI_NQ,
	IMPORTO_DA,
	IMPORTO_A,
	IMPORTOONERE,
	IMPORTOCONTABILEINUSCITA,
	IMPORTOCONTABILEININGRESSO,
	TX_ID_OPERAZIONE,
	TX_IMPORTO_NETTO,
	
	TX_BUTTON_MODELLO_CHANGED, TX_DATA_ACCR_DA, TX_DATA_ACCR_A,
	//PG150180_001 GG - inizio
	// campi del form di riconciliazione NODO
	ID_FLUSSO,
	DT_FLUSSO_DA_DAY,
	DT_FLUSSO_DA_MONTH,
	DT_FLUSSO_DA_YEAR,
	DT_FLUSSO_A_DAY,
	DT_FLUSSO_A_MONTH,
	DT_FLUSSO_A_YEAR,
	VERS_OGGETTO,
	IMP_PAGAMENTO_DA,
	IMP_PAGAMENTO_A,
	DT_REGOL,
	KEY_QUADRATURA,
	NOME_FILE_TXT,
	DT_CHIUSURAFLUSSO,
	STATO_SQUADRATURA,
	//PG150180_001 GG - fine
	TX_BUTTON_TIPOLSTRUT_CHANGED,	//PG180050_001 GG
	TX_RECUPERATE 		//PG200050_001 SB
	//inizio LP PG200200
	, DT_MAKEFLUSSO_DA_DAY
	, DT_MAKEFLUSSO_DA_MONTH
	, DT_MAKEFLUSSO_DA_YEAR
	, DT_MAKEFLUSSO_A_DAY
	, DT_MAKEFLUSSO_A_MONTH
	, DT_MAKEFLUSSO_A_YEAR
	, TIPOLOGIA_FLUSSO
	, SCARTATE_FLUSSO
	, RECUPERATE_FLUSSO
	, ESITO_INVIO_WS
	//fine LP PG200200
	, ESITO_INVIO_CONSERVAZIONE
	,TX_CODICE_FISCALE
	;
	
    private static ResourceBundle rb;

    public String format( Object... args ) {
        synchronized(Field.class) {
            if(rb==null)
                rb = ResourceBundle.getBundle(Field.class.getName());
            return MessageFormat.format(rb.getString(name()),args);
        }
    }
}
